#!/usr/bin/env python3
"""Transactional Windows, Mac reference, and Omarchy mouse profile controller."""
from contextlib import contextmanager
from copy import deepcopy
import argparse
import fcntl
import json
import math
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time
import uuid


class ControlError(RuntimeError):
    pass


NATIVE_OPTIONS = {"accel_profile": "str", "sensitivity": "float", "scroll_factor": "float",
                  "natural_scroll": "bool", "left_handed": "bool"}
MAC_DEFAULT = {"model": "sequoia-15.3.2", "tracking": 4, "natural_scroll": True, "left_handed": False}
WINDOWS_DEFAULT = {"speed": 10, "epp": True}
OMARCHY_DEFAULT = {"accel_profile": "", "sensitivity": 0.0, "scroll_factor": 1.0,
                   "natural_scroll": False, "left_handed": False}
PROFILE_DEFAULTS = {"omarchy": OMARCHY_DEFAULT, "mac": MAC_DEFAULT, "win": WINDOWS_DEFAULT}


def validate_native(native):
    if not isinstance(native, dict) or native.get("accel_profile") not in ("", "adaptive", "flat"):
        raise ControlError("Omarchy acceleration must be System, Adaptive, or Flat.")
    for key, low, high in (("sensitivity", -1, 1), ("scroll_factor", 0, 100)):
        value = native.get(key)
        if type(value) not in (int, float) or not math.isfinite(value) or not low <= value <= high:
            raise ControlError(f"Omarchy {key} must be a finite number from {low} to {high}.")
    for key in ("natural_scroll", "left_handed"):
        if type(native.get(key)) is not bool:
            raise ControlError(f"Omarchy {key} must be boolean.")
    return {key: native[key] for key in NATIVE_OPTIONS}


def migrate_config(config, native):
    config = deepcopy(config)
    if isinstance(config, dict) and config.get("version") == 1:
        config = deepcopy(config)
        config["version"] = 2
        if config.get("profile") == "default":
            config["profile"] = "omarchy"
        config["omarchy"] = validate_native(native)
    if isinstance(config, dict) and config.get("version") == 2:
        config["version"] = 3
        config["mac"] = deepcopy(MAC_DEFAULT)
    return validate(config)


def validate(config):
    if not isinstance(config, dict) or config.get("version") != 3:
        raise ControlError("Unsupported configuration file.")
    if config.get("profile") not in ("win", "mac", "omarchy"):
        raise ControlError("This version supports Win, Mac, and Omarchy.")
    win = config.get("windows", {})
    if type(win.get("speed")) is not int or not 1 <= win["speed"] <= 20:
        raise ControlError("Windows speed must be an integer from 1 to 20.")
    if type(win.get("epp")) is not bool:
        raise ControlError("EPP must be a boolean.")
    validate_native(config.get("omarchy"))
    mac = config.get("mac", {})
    if mac.get("model") != MAC_DEFAULT["model"]:
        raise ControlError("Unsupported Mac reference model.")
    if type(mac.get("tracking")) is not int or not 1 <= mac["tracking"] <= 10:
        raise ControlError("Mac tracking speed must be an integer from 1 to 10.")
    if any(type(mac.get(key)) is not bool for key in ("natural_scroll", "left_handed")):
        raise ControlError("Mac scroll and button options must be boolean.")
    return deepcopy(config)


def atomic_write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=".mouse-style-", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)


def write_json(path, value):
    atomic_write(path, json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def read_json(path):
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError) as exc:
        raise ControlError(f"{path.name} could not be read: {exc}") from exc


def render_lua(config):
    config = validate(config)
    win = config["windows"]
    native = ""
    if config["profile"] == "omarchy":
        native = "hl.config({ input = {\n" + "".join(
            f"  {key} = {json.dumps(value)},\n" for key, value in config["omarchy"].items()
            if key in NATIVE_OPTIONS) + "} })\n"
    elif config["profile"] == "mac":
        native = "hl.config({ input = {\n" + "".join(
            f"  {key} = {json.dumps(config['mac'][key])},\n" for key in ("natural_scroll", "left_handed")) + "} })\n"
    return ("-- Generated by Mouse Style. Change settings through the panel.\n" + native +
            "if hl.plugin.windows_pointer_linux then\n"
            "  hl.config({ plugin = { windows_pointer_linux = {\n"
            f'    pointer_speed = "{win["speed"]}/20",\n'
            f'    enhance_pointer_precision = {str(win["epp"]).lower()},\n'
            "  } } })\nend\n"
            "if hl.plugin.mouse_style_mac then\n"
            f'  hl.config({{ plugin = {{ mouse_style_mac = {{ tracking_speed = "{config["mac"]["tracking"]}" }} }} }})\n'
            "end\n")


class Hyprland:
    def __init__(self, plugin):
        self.plugin = plugin
        self.mac_plugin = plugin.with_name("mouse-style-mac.so")

    def available_profiles(self):
        return (["win"] if self.plugin.is_file() else []) + (["mac"] if self.mac_plugin.is_file() else []) + ["omarchy"]

    def run(self, *args, json_output=False):
        argv = ["hyprctl"] + (["-j"] if json_output else []) + list(args)
        try:
            result = subprocess.run(argv, text=True, capture_output=True, timeout=5, check=False)
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise ControlError(f"Hyprland did not respond: {exc}") from exc
        if result.returncode:
            raise ControlError((result.stderr or result.stdout).strip() or "Hyprland command failed.")
        if json_output:
            try:
                value = json.loads(result.stdout)
                if isinstance(value, dict) and "error" in value:
                    raise ControlError(str(value["error"]))
                return value
            except ValueError as exc:
                raise ControlError(result.stdout.strip() or "Hyprland returned an empty response.") from exc
        return result.stdout.strip()

    def native_settings(self):
        result = {key: self.run("getoption", f"input:{key}", json_output=True)[kind]
                  for key, kind in NATIVE_OPTIONS.items()}
        if result["accel_profile"] == "[[EMPTY]]":
            result["accel_profile"] = ""
        return validate_native(result)

    def snapshot(self):
        plugins = self.run("plugin", "list", json_output=True)
        if not isinstance(plugins, list):
            raise ControlError("Could not read the plugin list.")
        loaded = any(p.get("name") == "windows-pointer-linux" for p in plugins)
        mac_loaded = any(p.get("name") == "mouse-style-mac" for p in plugins)
        if loaded and mac_loaded:
            raise ControlError("Multiple pointer engines are loaded. Unload the last manually loaded engine first.")
        if mac_loaded:
            backend = self.run("mouse-style-mac", json_output=True)
            native = self.native_settings()
            mac = {"model": backend.get("model"), "tracking": backend.get("tracking_speed"),
                   "natural_scroll": native["natural_scroll"], "left_handed": native["left_handed"]}
            force = self.run("getoption", "input:force_no_accel", json_output=True)
            return {"profile": "mac" if force.get("bool") is False else "bypassed",
                    "windows": None, "omarchy": None, "mac": mac, "backend": backend}
        if loaded:
            backend = self.run("windows-pointer-linux", json_output=True)
            speed = backend.get("pointer_speed", "").split("/")[0]
            try:
                windows = {"speed": int(speed), "epp": backend.get("enhance_pointer_precision")}
                if not 1 <= windows["speed"] <= 20 or type(windows["epp"]) is not bool:
                    raise ValueError("Invalid Windows settings")
            except ValueError as exc:
                raise ControlError("Could not read Windows backend settings.") from exc
            force = self.run("getoption", "input:force_no_accel", json_output=True)
            return {"profile": "win" if force.get("bool") is False else "bypassed",
                    "windows": windows, "omarchy": None, "mac": None, "backend": backend}
        return {"profile": "omarchy", "windows": None, "omarchy": self.native_settings(), "mac": None, "backend": None}

    def preflight(self, config):
        errors = self.run("configerrors", json_output=True)
        if any(str(e).strip() for e in errors):
            raise ControlError("Resolve Hyprland configuration errors first: " + str(errors))
        force = self.run("getoption", "input:force_no_accel", json_output=True)
        if force.get("bool") is not False:
            raise ControlError("force_no_accel is enabled; disable it before using pointer profiles.")
        if config["profile"] == "win":
            if not self.plugin.is_file():
                raise ControlError("Windows backend not found. Install a compatible windows-pointer-linux build.")
        if config["profile"] == "mac" and not self.mac_plugin.is_file():
            raise ControlError("Mac reference backend not found. Build and install mouse-style-mac for this Hyprland version.")

    def apply(self, config):
        current = self.snapshot()
        binaries = {"win": self.plugin, "mac": self.mac_plugin}
        if current["profile"] != config["profile"]:
            if current["profile"] in binaries:
                self.run("plugin", "unload", str(binaries[current["profile"]]))
            if config["profile"] in binaries:
                self.run("plugin", "load", str(binaries[config["profile"]]))
        # Both native input and the Windows backend read settings on reload.
        # Win's Lua omits native overrides, restoring the user's base input config.
        self.run("reload", "config-only")
        self.verify(config)

    def verify(self, config):
        state = self.snapshot()
        if state["profile"] != config["profile"]:
            raise ControlError("The requested profile did not become active; restoring the previous settings.")
        if config["profile"] == "win" and state["windows"] != config["windows"]:
            raise ControlError("Windows settings could not be verified against the backend.")
        if config["profile"] == "mac" and state["mac"] != config["mac"]:
            raise ControlError("Mac settings could not be verified against the backend.")
        if config["profile"] == "omarchy":
            for key, value in config["omarchy"].items():
                actual = state["omarchy"][key]
                matches = math.isclose(actual, value, abs_tol=1e-6) if type(value) in (int, float) else actual == value
                if not matches:
                    raise ControlError(f"Omarchy {key} did not apply. Check later input overrides.")
        return state


class Controller:
    def __init__(self, home=None, backend=None):
        self.home = Path(home) if home else Path.home()
        self.state_dir = self.home / ".local/state/mouse-style"
        self.config_file = self.home / ".config/mouse-style/config.json"
        self.ui_file = self.home / ".config/mouse-style/ui.json"
        self.lua_file = self.home / ".config/hypr/mouse-style.lua"
        self.pending_file = self.state_dir / "preview.json"
        self.notice_file = self.state_dir / "notice.json"
        self.backend = backend or Hyprland(self.home / ".local/lib/hyprland/plugins/windows-pointer-linux.so")
        self.session = os.environ.get("HYPRLAND_INSTANCE_SIGNATURE", "")

    @contextmanager
    def lock(self):
        self.state_dir.mkdir(parents=True, exist_ok=True)
        with (self.state_dir / "controller.lock").open("a") as stream:
            # All command processes, including the independent rollback worker,
            # serialize mutations. Status cannot observe a half-applied profile.
            deadline = time.monotonic() + 3
            while True:
                try:
                    fcntl.flock(stream, fcntl.LOCK_EX | fcntl.LOCK_NB)
                    break
                except BlockingIOError:
                    if time.monotonic() >= deadline:
                        raise ControlError("A settings change is in progress. Try again shortly.")
                    time.sleep(0.05)
            yield

    def confirmed(self):
        config = read_json(self.config_file)
        if config.get("version") in (1, 2):
            return migrate_config(config, self.backend.native_settings() if config["version"] == 1 else None)
        return validate(config)

    def pending(self):
        return read_json(self.pending_file) if self.pending_file.exists() else None

    def ui_settings(self):
        settings = read_json(self.ui_file) if self.ui_file.exists() else {"bar_label": "code"}
        if not isinstance(settings, dict) or settings.get("bar_label") not in ("letter", "code", "hidden"):
            raise ControlError("Bar label must be Letter, Code, or Hidden.")
        return settings

    def set_bar_label(self, mode):
        if mode not in ("letter", "code", "hidden"):
            raise ControlError("Bar label must be Letter, Code, or Hidden.")
        settings = self.ui_settings()
        settings["bar_label"] = mode
        write_json(self.ui_file, settings)
        return self.status()

    def notice(self, text):
        write_json(self.notice_file, {"message": text})

    def write_lua(self, config):
        content = render_lua(config)
        if not self.lua_file.exists() or self.lua_file.read_text() != content:
            atomic_write(self.lua_file, content)

    def rollback(self, pending, message):
        previous = validate(pending["previous"])
        # The actual previous state, not just a possibly stale saved preference.
        self.write_lua(previous)
        self.backend.apply(previous)
        self.pending_file.unlink(missing_ok=True)
        self.notice(message)

    def expire(self):
        pending = self.pending()
        if pending and pending.get("session") == self.session and time.monotonic() >= pending["deadline"]:
            self.rollback(pending, "Trial expired. Previous settings restored.")

    def status(self):
        self.expire()
        confirmed = self.confirmed()
        runtime = self.backend.snapshot()
        pending = self.pending()
        if pending and pending.get("session") != self.session:
            raise ControlError("A trial from another session exists. Run mouse-style restore.")
        preferences = pending["candidate"] if pending else confirmed
        return {"ok": True, "profile": runtime["profile"], "confirmed": confirmed, "ui": self.ui_settings(),
                "windows": runtime["windows"] or preferences["windows"],
                "omarchy": runtime["omarchy"] or preferences["omarchy"],
                "mac": runtime["mac"] or preferences["mac"],
                "backend": runtime["backend"],
                "preview": {"token": pending["token"],
                            "seconds": max(0, math.ceil(pending["deadline"] - time.monotonic()))}
                           if pending else None,
                "message": read_json(self.notice_file)["message"] if self.notice_file.exists() else "",
                "available": self.backend.available_profiles()}

    def spawn_watchdog(self, token):
        subprocess.Popen([sys.executable, str(Path(__file__).resolve()), "watchdog", token],
                         stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                         stderr=subprocess.DEVNULL, start_new_session=True, close_fds=True)

    def preview(self, profile, speed=None, epp=None, spawn=True, native=None, mac=None, replace_token=None, defaults=False):
        self.expire()
        pending = self.pending()
        if replace_token is not None:
            if not pending or pending["token"] != replace_token or pending["session"] != self.session:
                raise ControlError("This trial is no longer active. Refresh the current state.")
            self.backend.verify(pending["candidate"])
        elif pending:
            raise ControlError("Keep or revert the current trial before starting another.")
        candidate = deepcopy(pending["candidate"]) if pending else self.confirmed()
        profile = "omarchy" if profile == "default" else profile
        candidate["profile"] = profile
        if defaults:
            if any(value is not None for value in (speed, epp, native, mac)):
                raise ControlError("Restore defaults cannot be combined with individual settings.")
            if profile not in PROFILE_DEFAULTS:
                raise ControlError("Defaults are available for Omarchy, Mac, and Win.")
            candidate["windows" if profile == "win" else profile] = deepcopy(PROFILE_DEFAULTS[profile])
        if profile != "win" and (speed is not None or epp is not None):
            raise ControlError("Windows settings can only be changed in the Win profile.")
        if native and profile != "omarchy":
            raise ControlError("Native settings can only be changed in the Omarchy profile.")
        if mac and profile != "mac":
            raise ControlError("Mac settings can only be changed in the Mac profile.")
        if speed is not None:
            candidate["windows"]["speed"] = speed
        if epp is not None:
            candidate["windows"]["epp"] = epp
        if native is not None:
            if any(key not in NATIVE_OPTIONS for key in native):
                raise ControlError("Unknown Omarchy setting.")
            candidate["omarchy"].update(native)
        if mac is not None:
            if any(key not in MAC_DEFAULT for key in mac):
                raise ControlError("Unknown Mac setting.")
            candidate["mac"].update(mac)
        validate(candidate)
        self.backend.preflight(candidate)
        actual = self.backend.snapshot()
        if actual["profile"] not in ("win", "mac", "omarchy"):
            raise ControlError("Cannot verify the active pointer path. No settings were changed.")
        if pending:
            # All edits in a trial share the ORIGINAL rollback anchor, including
            # style switches. A new token retires the previous rollback worker.
            previous = pending["previous"]
            if candidate == pending["candidate"]:
                return self.status()
        else:
            previous = self.confirmed()
            previous["profile"] = actual["profile"]
            for key in ("windows", "omarchy", "mac"):
                if actual[key]:
                    previous[key] = actual[key]
        if not pending and candidate == previous and candidate == self.confirmed():
            self.notice("These settings are already active and saved.")
            return self.status()
        token = uuid.uuid4().hex
        pending = {"token": token, "session": self.session, "previous": previous,
                   "candidate": candidate, "deadline": time.monotonic() + 15}
        write_json(self.pending_file, pending)
        try:
            # Spawn BEFORE applying; a UI/process failure must not strand a preview.
            if spawn:
                self.spawn_watchdog(token)
            self.write_lua(candidate)
            self.backend.apply(candidate)
            pending["deadline"] = time.monotonic() + 15
            write_json(self.pending_file, pending)
            self.notice("Applied. Keep saves your changes; each adjustment restarts the 15-second timer.")
        except Exception as exc:
            try:
                self.rollback(pending, "Change failed. Previous settings restored.")
            except Exception as rollback_error:
                raise ControlError(f"{exc}; rollback also failed: {rollback_error}") from exc
            raise ControlError(str(exc)) from exc
        return self.status()

    def confirm(self, token):
        self.expire()
        pending = self.pending()
        if not pending or pending["token"] != token or pending["session"] != self.session:
            raise ControlError("This trial is no longer active. Refresh the current state.")
        self.backend.verify(pending["candidate"])
        # Atomically remove rollback authority before committing; if interrupted
        # before the write, next login restores the previous confirmed preference.
        self.pending_file.unlink()
        try:
            write_json(self.config_file, pending["candidate"])
        except Exception:
            self.rollback(pending, "Could not save. Previous settings restored.")
            raise
        self.notice("Saved. This profile will also be restored next session.")
        return self.status()

    def revert(self, token):
        pending = self.pending()
        if not pending or pending["token"] != token or pending["session"] != self.session:
            raise ControlError("There is no matching active trial to revert.")
        self.rollback(pending, "Previous settings restored.")
        return self.status()

    def restore(self):
        config = self.confirmed()
        self.pending_file.unlink(missing_ok=True)
        try:
            self.backend.preflight(config)
            self.write_lua(config)
            self.backend.apply(config)
        except Exception as exc:
            # A compositor upgrade may reject the old binary. Leave native motion.
            fallback = deepcopy(config)
            fallback["profile"] = "omarchy"
            try:
                self.write_lua(fallback)
                self.backend.apply(fallback)
            except Exception:
                pass
            self.notice(f"Could not restore the saved profile: {exc}")
            raise
        self.notice("")
        return self.status()


def watchdog(controller, token):
    # Runs independently of Quickshell, including when the panel is closed.
    # Lock contention while an action is in flight is retried, not treated as success.
    for _ in range(90):
        time.sleep(0.5)
        try:
            with controller.lock():
                pending = controller.pending()
                if not pending or pending["token"] != token or pending["session"] != controller.session:
                    return
                controller.expire()
                if not controller.pending():
                    return
        except (ControlError, OSError):
            continue


def main():
    if len(sys.argv) > 1 and sys.argv[1] in ("setup", "repair", "uninstall"):
        from setup import main as setup_main
        action = sys.argv.pop(1)
        if action == "uninstall":
            sys.argv.insert(1, "--uninstall")
        return setup_main()
    parser = argparse.ArgumentParser(description=__doc__)
    subs = parser.add_subparsers(dest="command", required=True)
    subs.add_parser("status")
    subs.add_parser("restore")
    subs.add_parser("bar-label").add_argument("mode", choices=("letter", "code", "hidden"))
    trial = subs.add_parser("preview")
    trial.add_argument("profile", choices=("win", "mac", "omarchy", "default"))
    trial.add_argument("--speed", type=int)
    trial.add_argument("--epp", choices=("on", "off"))
    trial.add_argument("--accel", choices=("system", "adaptive", "flat"))
    trial.add_argument("--sensitivity", type=float)
    trial.add_argument("--scroll-factor", type=float)
    trial.add_argument("--natural-scroll", choices=("on", "off"))
    trial.add_argument("--left-handed", choices=("on", "off"))
    trial.add_argument("--tracking", type=int)
    trial.add_argument("--defaults", action="store_true", help="Restore only this profile's default settings as a trial.")
    trial.add_argument("--replace-token", help="Adjust an active trial while keeping its original rollback settings.")
    for name in ("confirm", "revert", "watchdog"):
        subs.add_parser(name).add_argument("token")
    args = parser.parse_args()
    controller = Controller()
    try:
        if args.command == "watchdog":
            watchdog(controller, args.token)
            return 0
        with controller.lock():
            if args.command == "preview":
                native = {}
                if args.accel is not None:
                    native["accel_profile"] = "" if args.accel == "system" else args.accel
                for key in ("sensitivity", "scroll_factor"):
                    if getattr(args, key) is not None:
                        native[key] = getattr(args, key)
                for key in ("natural_scroll", "left_handed"):
                    if getattr(args, key) is not None:
                        native[key] = getattr(args, key) == "on"
                mac = {}
                if args.profile == "mac":
                    if args.accel is not None or args.sensitivity is not None or args.scroll_factor is not None:
                        raise ControlError("Mac uses tracking speed, not Omarchy acceleration/sensitivity settings.")
                    mac, native = native, {}
                if args.tracking is not None:
                    mac["tracking"] = args.tracking
                result = controller.preview(args.profile, args.speed,
                                            None if args.epp is None else args.epp == "on", native=native or None, mac=mac or None,
                                            replace_token=args.replace_token, defaults=args.defaults)
            elif args.command == "bar-label":
                result = controller.set_bar_label(args.mode)
            elif args.command in ("confirm", "revert"):
                result = getattr(controller, args.command)(args.token)
            else:
                result = getattr(controller, args.command)()
        print(json.dumps(result, ensure_ascii=False))
        return 0
    except (ControlError, OSError, KeyError, TypeError, ValueError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False))
        return 1


if __name__ == "__main__":
    sys.exit(main())
